version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - GOPROXY=https://goproxy.cn,direct
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./static:/root/static
      - ./certs:/root/certs
      - ./uploads:/root/uploads
      - ./configs:/root/configs:ro
    environment:
      - SHS_DATABASE_HOST=mysql
      - SHS_DATABASE_USER=app
      - SHS_DATABASE_PASSWORD=password
      - SHS_DATABASE_DBNAME=static_hosting
      - SHS_SERVER_DOMAIN=localhost:8080
      - TZ=Asia/Shanghai
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    # 改进健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=static_hosting
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
      - TZ=Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/docker-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network
    # 优化 MySQL 性能和兼容性
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=256M
      --max-connections=100
      --innodb-log-file-size=128M
      --innodb-flush-log-at-trx-commit=2
      --sync-binlog=0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
